APP_NAME = compass-console
APP_PATH = compass
BUILDPACK = eu.gcr.io/kyma-project/test-infra/buildpack-node:v20200428-02dd40a1
SCRIPTS_DIR = $(realpath $(shell pwd)/..)/scripts

include app/scripts/makefile-node-common.mk
